class CfgMovesAnimal_Base_F
{
	access = 1;
	collisionGeomCompPattern[] = {1};
	collisionVertexPattern[] = {};
	transitionsDisabled[] = {};
	transitionsInterpolated[] = {};
	transitionsSimple[] = {};
	class Actions
	{
		class NoActions: ManActions
		{
			limitFast = 5.5;
			stance = "ManStanceUndefined";
			turnSpeed = 8;
			upDegree = 0;
			useFastMove = 0;
		};
	};
	class BlendAnims
	{
		aimingDefault[] = {"head", 1};
		aimingNo[] = {};
		aimingUpDefault[] = {};
		headDefault[] = {"Head", 1};
		headNo[] = {};
		legsDefault[] = {};
		legsNo[] = {};
		untiltWeaponDefault[] = {};
	};
	class Default
	{
		access = 3;
		aiming = "aimingNo";
		aimingBody = "aimingUpDefault";
		aimPrecision = 1;
		boundingSphere = 1;
		canPullTrigger = 1;
		canreload = 1;
		collisionShapeSafe = "";
		connectAs = "";
		connectFrom[] = {};
		connectTo[] = {};
		disableWeapons = 1;
		disableWeaponsLong = 0;
		duty = -0.51;
		enableAutoActions = 0;
		enableBinocular = 0;
		enableDirectControl = 1;
		enableMissile = 0;
		enableOptics = 1;
		equivalentTo = "";
		file = "";
		forceAim = 0;
		hasCollShapeSafe = 0;
		head = "headDefault";
		headBobMode = 1;
		headBobStrength = 0.5;
		interpolateFrom[] = {};
		interpolateTo[] = {};
		interpolateWith[] = {};
		interpolationRestart = 0;
		interpolationSpeed = 6;
		leaning = "aimingNo";
		leaningCorrectionAngleBeg = 0;
		leaningCorrectionAngleEnd = 0;
		leaningFactorBeg = 0;
		leaningFactorEnd = 0;
		leaningFactorZeroPoint = -1;
		leftHandIKBeg = 0;
		leftHandIKCurve = 0;
		leftHandIKEnd = 0;
		legs = "legsNo";
		limitGunMovement = 1;
		looped = 1;
		onLadder = 0;
		onLandBeg = 0;
		onLandEnd = 0;
		predictSpeedCoef = 1;
		preload = 0;
		relSpeedMax = 1;
		relSpeedMin = 1;
		rightHandIKBeg = 0;
		rightHandIKCurve = 0;
		rightHandIKEnd = 0;
		showDisposableGun = 0;
		showHandGun = 0;
		showItemInHand = 0;
		showItemInRightHand = 0;
		showWeaponAim = 1;
		soundEdge[] = {0.5, 1};
		soundEdge1 = 0.5;
		soundEdge2 = 1;
		soundEnabled = 1;
		soundOverride = "";
		speed = 0.5;
		terminal = 0;
		untiltWeapon = "aimingNo";
		variantAfter[] = {5, 10, 20};
		variantsAI[] = {};
		variantsPlayer[] = {};
		visibleSize = 1;
		walkcycles = 1;
		weaponIK = 0;
	};
	class DefaultDie: Default
	{
		aiming = "aimingNo";
		head = "headNo";
		legs = "legsNo";
	};
	class Interpolations {};
	class ManActions
	{
		BinocOff = "";
		BinocOn = "";
		CanNotMove = "";
		Civil = "";
		CivilLying = "";
		Combat = "";
		Crouch = "";
		Default = "";
		Die = "";
		Down = "";
		Eat = "";
		EvasiveBack = "";
		EvasiveForward = "";
		EvasiveLeft = "";
		EvasiveRight = "";
		FastB = "";
		FastF = "";
		FastL = "";
		FastLB = "";
		FastLF = "";
		FastR = "";
		FastRB = "";
		FastRF = "";
		FireNotPossible = "";
		GetInHigh = "";
		GetInLow = "";
		GetInMedium = "";
		GetOutHigh = "";
		GetOutLow = "";
		GetOutMedium = "";
		HandGunOn = "";
		JumpOff = "";
		LadderOff = "";
		LadderOffBottom = "";
		LadderOffTop = "";
		LadderOnDown = "";
		LadderOnUp = "";
		LookAround = "";
		Lying = "";
		Medic = "";
		PlayerCrouch = "";
		PlayerProne = "";
		PlayerStand = "";
		PutDown = "";
		PutDownEnd = "";
		ReloadAT = "";
		ReloadMagazine = "";
		ReloadMGun = "";
		ReloadMortar = "";
		Rest = "";
		Salute = "";
		SitDown = "";
		SlowB = "";
		SlowF = "";
		SlowL = "";
		SlowLB = "";
		SlowLF = "";
		SlowR = "";
		SlowRB = "";
		SlowRF = "";
		Stand = "";
		StartSwim = "";
		Stop = "";
		StopEat = "";
		StopRelaxed = "";
		StopRest = "";
		StopSwim = "";
		StrokeFist = "";
		StrokeGun = "";
		TakeFlag = "";
		ThrowGrenade = "";
		Treated = "";
		TurnL = "";
		TurnLRelaxed = "";
		TurnR = "";
		TurnRRelaxed = "";
		Up = "";
		WalkB = "";
		WalkF = "";
		WalkL = "";
		WalkLB = "";
		WalkLF = "";
		WalkR = "";
		WalkRB = "";
		WalkRF = "";
		WeaponOff = "";
		WeaponOn = "";
	};
	class StandBase: Default
	{
		disableWeapons = 1;
		disableWeaponsLong = 1;
		duty = -1;
		enableDirectControl = 0;
		head = "headDefault";
		looped = 1;
		relSpeedMax = 1.1;
		relSpeedMin = 0.7;
		soundEnabled = 1;
		speed = 1e+010;
	};
};
