class CfgMovesWomen: CfgMovesBasic
{
	class ManActions
	{
		ChopperHeavy_C_Straight_static_H = "crew";
		ChopperHeavy_L_GetIn_H = "crew";
		ChopperHeavy_L_GetOut_H = "crew";
		ChopperHeavy_L_Static_H = "crew";
		ChopperHeavy_LP_Static_H = "crew";
		ChopperHeavy_Lux_GetIn_H = "crew";
		chopperheavy_Lux_getout_H = "crew";
		ChopperHeavy_R_GetIn_H = "crew";
		ChopperHeavy_R_GetOut_H = "crew";
		ChopperHeavy_R_static_H = "crew";
		chopperLight_C_L_idleA_H = "ChopperLight_C_L_wmn_static_H";
		chopperLight_C_L_idleB_H = "ChopperLight_C_L_wmn_static_H";
		chopperLight_C_L_idleC_H = "ChopperLight_C_L_wmn_static_H";
		chopperLight_C_L_idleD_H = "ChopperLight_C_L_wmn_static_H";
		chopperLight_C_L_static_H = "ChopperLight_C_L_wmn_static_H";
		chopperLight_C_LIn_H = "ChopperLight_C_L_wmn_static_H";
		chopperLight_C_LOut_H = "ChopperLight_C_L_wmn_static_H";
		chopperLight_C_R_idleA_H = "ChopperLight_C_R_wmn_static_H";
		chopperLight_C_R_idleB_H = "ChopperLight_C_R_wmn_static_H";
		chopperLight_C_R_idleC_H = "ChopperLight_C_R_wmn_static_H";
		chopperLight_C_R_idleD_H = "ChopperLight_C_R_wmn_static_H";
		chopperLight_C_R_static_H = "ChopperLight_C_R_wmn_static_H";
		chopperLight_C_Rin_H = "ChopperLight_C_R_wmn_static_H";
		chopperLight_C_Rout_H = "ChopperLight_C_R_wmn_static_H";
		chopperLight_CB_getin_fromErcRflLow_H = "";
		chopperLight_CB_getout_toErcRflLow_H = "";
		chopperLight_CB_idle1shaky_H = "";
		chopperLight_CB_idle1stable_H = "";
		chopperLight_CB_idle2lookleft_H = "";
		chopperLight_CB_idle3lookright_H = "";
		chopperLight_CB_idle4_H = "";
		chopperLight_CB_idle5lookdown_H = "";
		chopperLight_CB_idle6pointing_H = "";
		chopperLight_CB_idle7lookaround_H = "";
		chopperLight_CB_static_H = "";
		chopperLight_L_buttonPush_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_greetFront_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_greetLeft_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_greetRight_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_HeadInHand_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_headSetOff_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_headSetOn_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_idleLoopA_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_idleLoopB_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_idleLoopC_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_idleLoopD_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_idleLoopE_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_In_H = "Crew";
		chopperLight_L_lookLeft_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_lookLeftBackUp_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_lookRight_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_lookRightBackUp_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_out_H = "Crew";
		chopperLight_L_pointFront_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_pointLeft_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_pointRight_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_seatBeltOff_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_seatBeltOn_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_static_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_switchOff_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_switchOn_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_thumbDownFront_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_thumbDownLeft_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_thumbDownRight_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_thumbUpFront_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_thumbUpLeft_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_thumbUpRight_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_tweakHeadSetMicA_H = "ChopperLight_L_wmn_static_H";
		chopperLight_L_tweakHeadSetMicB_H = "ChopperLight_L_wmn_static_H";
		chopperLight_R_buttonPush_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_copilot_to_passenger_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_greetFront_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_greetLeft_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_greetRight_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_HeadInHand_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_headSetOff_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_headSetOn_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_idleLoopA_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_idleLoopB_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_idleLoopC_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_idleLoopD_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_idleLoopE_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_in_H = "Crew";
		chopperLight_R_lookLeft_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_lookLeftBackUp_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_lookRight_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_lookRightBackUp_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_out_H = "Crew";
		chopperLight_R_pointFront_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_pointLeft_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_pointRight_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_seatBeltOff_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_seatBeltOn_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_static_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_switchOff_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_switchOn_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_thumbDownFront_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_thumbDownLeft_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_thumbDownRight_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_thumbUpFront_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_thumbUpLeft_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_R_thumbUpRight_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_bothThumbsUp_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_copilot_to_cameraHold_1_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_copilot_to_cameraHold_2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_filmingF_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_filmingL_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_filmingR1_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_filmingR2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_hold_to_copilot_1_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_hold_to_copilot_2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_idle_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_lowerStanceLoop_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_lowerStanceToCamPose_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_malfunction_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_camera_toLowerStance_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_copilot_to_cellHold_1_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_copilot_to_cellHold_2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_dial_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_hold_to_copilot_1_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_hold_to_copilot_2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_idle2talkingToPilot_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_idle3_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_idle4_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_idle_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_cell_talkToCell_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_CongratsToPilot_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_grumbling_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleA_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleBored_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleBoredB_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleCtalk_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleDtalk_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleE_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleF_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleG_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleH_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_idleI_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_LittleNervous_scratching_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_LittleNervous_watchClockA_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_LittleNervous_watchClockB_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_lookingAround_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_musicA_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_musicB_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_musicC_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_NoFront_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_NoLeft_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_NoRight_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pad_copilot_to_padHold_1_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pad_copilot_to_padHold_2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pad_hold_to_copilot_1_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pad_hold_to_copilot_2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pad_idle_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pad_typing1_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pad_typing2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pad_typing3_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_passenger_to_copilot_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_POIfront_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_POIfrontB_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_POIleft_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_pointingAheadTalking_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_POIright_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_replyToPilot2_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_replyToPilot_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_replyToPilotAgree_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_scaredA_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_scaredB_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_scaredDin_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_scaredDloop_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_scaredDout_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_scratching_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_seatBeltOff_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_seatBeltOn_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_sneezingCoughing_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_static_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_talkIntercom_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_talkRightOut_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_talkToPilotConsideringProposal_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_talkToPilotFlyAhead_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_talkToPilotNoProblemAtall_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_tellingStory_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_tinyNervous_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_tinyNervousB_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_tiredA_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_tiredB_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_watchClock_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_YesFront_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_YesLeft_H = "ChopperLight_RP_wmn_static_H";
		chopperLight_RP_YesRight_H = "ChopperLight_RP_wmn_static_H";
		Mk201_Turret = "";
		Mk34_Turret = "";
		Mortar_01_F_Turret = "";
		Static_Turret = "";
		Truck_02_Driver = "Crew";
		Truck_Cargo01 = "Crew";
		Truck_Cargo02 = "Crew";
		Truck_Cargo03 = "Crew";
		Truck_Cargo04 = "Crew";
		Truck_Driver = "Crew";
	};
	class States
	{
		class ChopperLight_C_L_wmn_static_H: Crew
		{
			file = "\A3\Air_F\Heli_Light_01\Data\Anim\wmn\C_L_static.rtm";
			interpolateTo[] = {"KIA_chopperLight_C_L_wmn_H", 1};
			looped = 0;
		};
		class ChopperLight_C_R_wmn_static_H: Crew
		{
			file = "\A3\Air_F\Heli_Light_01\Data\Anim\wmn\C_R_static.rtm";
			interpolateTo[] = {"KIA_chopperLight_C_R_wmn_H", 1};
			looped = 0;
		};
		class ChopperLight_L_wmn_static_H: Crew
		{
			file = "\A3\Air_F\Heli_Light_01\Data\Anim\wmn\L_static.rtm";
			interpolateTo[] = {"KIA_chopperLight_L_wmn_H", 1};
			looped = 0;
			speed = 1e+010;
		};
		class ChopperLight_RP_wmn_static_H: Crew
		{
			file = "\A3\Air_F\Heli_Light_01\Data\Anim\wmn\RP_static.rtm";
			interpolateTo[] = {"KIA_chopperLight_RP_wmn_H", 1};
			looped = 0;
			speed = 1e+010;
		};
		class Crew {};
		class KIA_chopperLight_C_L_wmn_H: KIA_chopperLight_L_wmn_H
		{
			file = "\A3\Air_F\Heli_Light_01\Data\Anim\wmn\C_L_death.rtm";
		};
		class KIA_chopperLight_C_R_wmn_H: KIA_chopperLight_L_wmn_H
		{
			file = "\A3\Air_F\Heli_Light_01\Data\Anim\wmn\C_R_death.rtm";
		};
		class KIA_chopperLight_L_wmn_H: DefaultDie
		{
			actions = "DeadActions";
			connectTo[] = {"Unconscious", 0.1};
			file = "\A3\Air_F\Heli_Light_01\Data\Anim\wmn\L_death.rtm";
			looped = 0;
			soundEnabled = 0;
			speed = 1e+010;
			terminal = 1;
		};
		class KIA_chopperLight_RP_wmn_H: KIA_chopperLight_L_wmn_H
		{
			file = "\A3\Air_F\Heli_Light_01\Data\Anim\wmn\RP_death.rtm";
		};
	};
};
