class CowsSlot_Rail: CowsSlot
{
	class compatibleItems
	{
		optic_aco = 1;
		optic_ACO_grn = 1;
		optic_ACO_grn_smg = 1;
		optic_aco_smg = 1;
		optic_ams = 1;
		optic_AMS_khk = 1;
		optic_AMS_snd = 1;
		optic_Arco = 1;
		optic_Arco_AK_arid_F = 1;
		optic_Arco_AK_blk_F = 1;
		optic_Arco_AK_lush_F = 1;
		optic_Arco_arid_F = 1;
		optic_Arco_blk_F = 1;
		optic_Arco_ghex_F = 1;
		optic_Arco_lush_F = 1;
		optic_DMS = 1;
		optic_DMS_ghex_F = 1;
		optic_DMS_weathered_F = 1;
		optic_DMS_weathered_Kir_F = 1;
		optic_ERCO_blk_F = 1;
		optic_ERCO_khk_F = 1;
		optic_ERCO_snd_F = 1;
		optic_hamr = 1;
		optic_Hamr_khk_F = 1;
		optic_Holosight = 1;
		optic_Holosight_arid_F = 1;
		optic_Holosight_blk_F = 1;
		optic_Holosight_khk_F = 1;
		optic_Holosight_lush_F = 1;
		optic_Holosight_smg = 1;
		optic_Holosight_smg_blk_F = 1;
		optic_Holosight_smg_khk_F = 1;
		optic_KHS_blk = 1;
		optic_KHS_hex = 1;
		optic_KHS_old = 1;
		optic_KHS_tan = 1;
		optic_LRPS = 1;
		optic_LRPS_ghex_F = 1;
		optic_LRPS_tna_F = 1;
		optic_MRCO = 1;
		optic_Nightstalker = 1;
		optic_NVS = 1;
		optic_SOS = 1;
		optic_SOS_khk_F = 1;
		optic_tws = 1;
		optic_tws_mg = 1;
	};
};
