class RscMapSpectrum: RscMapControlEmpty
{
	h = "safezoneH";
	onLoad = "_this call (uinamespace getvariable 'bin_fnc_drawSpectrum');";
	scaleMax = 0.4;
	scaleMin = 0.004;
	show = 0;
	w = "safezoneWAbs";
	x = "safezoneXAbs";
	y = "safezoneY";
	class Spectrum
	{
		class IconRectangles
		{
			class GammaGradient
			{
				color[] = {0.7, 0.7, 0, 1};
				frequency[] = {1e+020, 1e+021};
				h = 0.04;
				texture = "\a3\UI_F_Contact\Data\Common\RscMapSpectrum\gradient_left_gs.paa";
				tooltipText = "In nature, gamma rays are created by radioactive decay and are extremely dangerous to humans.";
				tooltipTitle = "Gamma Rays";
				y = 0.85;
			};
			class RadioGradient
			{
				color[] = {0.9, 0.4, 0.2, 1};
				frequency[] = {3, 3000};
				h = 0.04;
				texture = "\a3\UI_F_Contact\Data\Common\RscMapSpectrum\gradient_right_gs.paa";
				tooltipText = "As the name suggests, radio waves were first used for radios and later, television and military communications. They are widely used for transmitting information over long distances. Frequencies are strictly regulated by governments and international bodies.";
				tooltipTitle = "Radio Waves";
				y = 0.85;
			};
			class VisibleLight
			{
				color[] = {1, 1, 1, 1};
				frequency[] = {4.3e+014, 7.7e+014};
				h = 0.04;
				layer = 0;
				text = "Visible Light";
				textOffset = 1.75;
				texture = "\a3\UI_F_Contact\Data\Common\RscMapSpectrum\visibleLight_co.paa";
				tooltipText = "Electromagnetic waves visible to the human eye, perceived as colors by our brain. This is everything we see around us.";
				tooltipTitle = "Visible Light";
				y = 0.85;
			};
		};
		class Rectangles
		{
			class AM: FM
			{
				frequency[] = {535000, 1.605e+006};
				text = "AM Radio";
				tooltipFrequencyOffset = -1;
				tooltipText = "AM means 'Amplitude Modulation'. It conveys sound by changing a signal's strength, which makes it particularly vulnerable to static interference. Widespread during the 'Golden Age of Radio', its popularity waned as FM radio became more common.";
			};
			class CellPhone1: FM
			{
				frequency[] = {8.24e+008, 8.94e+008};
				layer = 0;
				layerText = 1;
				text = "Cell Phones";
				tooltipFrequencyOffset = -1;
				tooltipText = "This is the frequency dominated by mobile phones. Bands on lower frequencies allow companies to cover larger areas, while those on higher frequencies are useful for serving customers across smaller regions.";
			};
			class CellPhone2: CellPhone1
			{
				frequency[] = {1.85e+009, 1.99e+009};
			};
			class EHF: ELF
			{
				frequency[] = {3e+010, 3e+011};
				text = "EHF";
				tooltipText = "EHF is sometimes referred to as the millimeter band. It is used in radars, point-to-point communications, and airport security screening.";
				tooltipTitle = "Extremely High Frequency";
			};
			class ELF
			{
				color[] = {1, 1, 1, 0.2};
				frequency[] = {3, 30};
				h = 0.04;
				layer = 0;
				text = "ELF";
				textOffset = 0;
				tooltipText = "These are generated by lightning and disturbances in Earth's magnetic fields.";
				tooltipTitle = "Extremely Low Frequency";
				y = 0.78;
			};
			class FM
			{
				color[] = {1, 1, 1, 0.3};
				frequency[] = {8.8e+007, 1.08e+008};
				h = 0.04;
				layer = 0;
				text = "FM Radio";
				textOffset = 1.75;
				tooltipText = "FM stands for 'Frequency Modulation', which means that sound is transmitted by the constant changing of a signal's frequency. A radio station operating on 88.2 MHz, for example, may in fact be using a band between 88.1 and 88.3 MHz.";
				y = 0.65;
			};
			class GammaRays: MicroWaves
			{
				color[] = {0.7, 0.7, 0, 1};
				frequency[] = {3e+018, 1e+020};
				text = "Gamma Rays";
				tooltipText = "In nature, gamma rays are created by radioactive decay and are extremely dangerous to humans.";
				tooltipTitle = "Gamma Rays";
			};
			class HF: ELF
			{
				frequency[] = {3e+006, 3e+007};
				text = "HF";
				tooltipText = "High Frequencies propagate through 'skywave', where the signal is reflected from the ionosphere and can travel beyond the horizon. These are employed in aviation, military, and amateur radio communications.";
				tooltipTitle = "High Frequency";
			};
			class IEEE_C: IEEE_L
			{
				frequency[] = {4e+009, 8e+009};
				text = "C";
				tooltipTitle = "C Band";
			};
			class IEEE_G: IEEE_S
			{
				frequency[] = {1.1e+011, 3e+011};
				text = "G";
				tooltipTitle = "G Band";
			};
			class IEEE_K: IEEE_S
			{
				frequency[] = {1.8e+010, 2.7e+010};
				text = "K";
				tooltipTitle = "K Band";
			};
			class IEEE_Ka: IEEE_L
			{
				frequency[] = {2.7e+010, 4e+010};
				text = "Ka";
				tooltipTitle = "Ka Band";
			};
			class IEEE_Ku: IEEE_L
			{
				frequency[] = {1.2e+010, 1.8e+010};
				text = "Ku";
				tooltipTitle = "Ku Band";
			};
			class IEEE_L: SHF
			{
				frequency[] = {1e+009, 2e+009};
				h = 0.04;
				text = "L";
				tooltipText = "This is an older NATO designation of a frequency band.";
				tooltipTitle = "L Band";
				y = 0.73;
			};
			class IEEE_S: EHF
			{
				frequency[] = {2e+009, 4e+009};
				h = 0.04;
				text = "S";
				tooltipText = "This is an older NATO designation of a frequency band.";
				tooltipTitle = "S Band";
				y = 0.73;
			};
			class IEEE_V: IEEE_S
			{
				frequency[] = {4e+010, 7.5e+010};
				text = "V";
				tooltipTitle = "V Band";
			};
			class IEEE_W: IEEE_L
			{
				frequency[] = {7.5e+010, 1.1e+011};
				text = "W";
				tooltipTitle = "W Band";
			};
			class IEEE_X: IEEE_S
			{
				frequency[] = {8e+009, 1.2e+010};
				text = "X";
				tooltipTitle = "X Band";
			};
			class Infrared: RadioWaves
			{
				color[] = {0.65098, 0.0313726, 0.176471, 1};
				frequency[] = {3e+012, 4.3e+014};
				text = "Infrared";
				tooltipText = "Infrared radiation is known for transmitting heat and has many civil and military applications, ranging from thermal imaging, weather forecasting and spectroscopy to missile homing, tracking and night vision optics.";
				tooltipTitle = "Infrared Radiation";
			};
			class Laser: FM
			{
				frequency[] = {4e+014, 7e+014};
				text = "Laser";
				tooltipText = "Lasers are highly amplified light beams in infrared and visible spectra. They are used for range calculations and targeting by the military, and by civilians for barcode scanning, surgery, cutting, welding, and exercising cats...";
			};
			class LF: ELF
			{
				frequency[] = {30000, 300000};
				text = "LF";
				tooltipText = "Low Frequencies can travel considerable distances owing to their ability to diffract across terrain and travel beyond the horizon - a method known as 'ground wave' propagation. These are employed by radio navigation and meteorological information broadcasts.";
				tooltipTitle = "Low Frequency";
			};
			class MF: SLF
			{
				frequency[] = {300000, 3e+006};
				text = "MF";
				tooltipText = "Apart from the widely known AM radio, this band also includes maritime communications and distress beacons.";
				tooltipTitle = "Medium Frequency";
			};
			class MicroWaves: RadioWaves
			{
				color[] = {0.4, 0.68, 0.85, 1};
				frequency[] = {3e+008, 3e+012};
				text = "Microwaves";
				tooltipText = "Microwaves, like radio waves, are used mainly for communication. Their shorter wavelength allows for smaller antennas and a larger bitrate - but also require line of sight. They are the preferred medium for radars and remote sensing.";
				tooltipTitle = "Microwaves";
			};
			class RadioWaves
			{
				color[] = {0.9, 0.4, 0.2, 1};
				colorText[] = {1, 1, 1, 1};
				frequency[] = {3000, 3e+008};
				h = 0.04;
				layer = 0;
				text = "Radio Waves";
				textOffset = 0;
				tooltipText = "As the name suggests, radio waves were first used for radios and later, television and military communications. They are widely used for transmitting information over long distances. Frequencies are strictly regulated by governments and international bodies.";
				tooltipTitle = "Radio Waves";
				y = 0.85;
			};
			class SHF: SLF
			{
				frequency[] = {3e+009, 3e+010};
				text = "SHF";
				tooltipText = "Super High Frequencies are utilized by some types of radar and they are essential for microwave heating - including microwave ovens.";
				tooltipTitle = "Super High Frequency";
			};
			class SLF: ELF
			{
				color[] = {1, 1, 1, 0.3};
				frequency[] = {30, 300};
				text = "SLF";
				tooltipText = "This frequency can penetrate seawater hundreds of meters deep, which is frequently put to use in submarine communications. However, it requires extremely large antennas to transmit and receive.";
				tooltipTitle = "Super Low Frequency";
			};
			class TI: FM
			{
				frequency[] = {2.1e+013, 3.3e+013};
				text = "TI";
				tooltipText = "Thermal Imaging (TI), occasionally known as FLIR (Forward-Looking InfraRed), has a variety of military applications, especially in terms of recon and targeting.";
				tooltipTitle = "Thermal Imaging";
			};
			class TV1: FM
			{
				frequency[] = {4e+007, 8.7e+007};
				layer = 0;
				layerText = 1;
				text = "TV";
				tooltipText = "Here we have the band for television channels. Because video and sound need more data, every channel requires a wider frequency band, and the number of these is limited - leading to competition over unallocated bands.";
			};
			class TV2: TV1
			{
				frequency[] = {1.74e+008, 2.3e+008};
			};
			class UHF: ELF
			{
				frequency[] = {3e+008, 3e+009};
				text = "UHF";
				tooltipText = "These are predominantly used for television broadcasting, cell phones, satellite communications (including GPS), Wi-Fi, and many other systems that need to transmit large amounts of data.";
				tooltipTitle = "Ultra High Frequency";
			};
			class ULF: ELF
			{
				frequency[] = {300, 3000};
				text = "ULF";
				tooltipText = "Ultra Low Frequencies can move through soil and are sometimes used for mining communications.";
				tooltipTitle = "Ultra Low Frequency";
			};
			class Ultraviolet: MicroWaves
			{
				color[] = {0.647059, 0.133333, 0.533333, 1};
				frequency[] = {7.7e+014, 3e+016};
				text = "Ultraviolet";
				tooltipText = "These are produced by black lights, tanning lamps, and also by our sun. Though they are mostly absorbed by Earth's atmosphere, prolonged exposure can still be harmful to people.";
				tooltipTitle = "Ultraviolet Radiation";
			};
			class VHF: SLF
			{
				frequency[] = {3e+007, 3e+008};
				text = "VHF";
				tooltipText = "For this band, antennas can be small enough to be made man-portable. They are used for FM radio, television, military handhelds, and countless other communication devices.";
				tooltipTitle = "Very High Frequency";
			};
			class VLF: SLF
			{
				frequency[] = {3000, 30000};
				text = "VLF";
				tooltipText = "Used for radio navigation or radio clocks, and was used for wireless telegraphy in early 20th century.";
				tooltipTitle = "Very Low Frequency";
			};
			class WiFi1: FM
			{
				frequency[] = {2.4e+009, 2.48e+009};
				layerText = 1;
				text = "Wi-Fi";
				tooltipText = "Today, the frequency of wireless Internet connects countless digital devices. Being at the higher end of the spectrum its range is limited, but it does allow larger bitrates.";
			};
			class WiFi2: WiFi1
			{
				frequency[] = {5e+009, 5.7e+009};
			};
			class XRays: RadioWaves
			{
				color[] = {0.4, 0.7, 0.4, 1};
				frequency[] = {3e+016, 3e+018};
				text = "X-Rays";
				tooltipText = "X-rays pass through most objects, making them useful for generating images of tissue and structures inside the human body. They are also used in astronomy for observing stars and black holes.";
				tooltipTitle = "X-Rays";
			};
		};
	};
};
