class RscTestControlTypes
{
	closeOnMissionEnd = 0;
	enableDisplay = 0;
	enableSimulation = 0;
	idd = 999;
	onLoad = "[""onLoad"",_this,""RscTestControlTypes"",'GUI'] call 	(uinamespace getvariable 'BIS_fnc_initDisplay')";
	onUnload = "[""onUnload"",_this,""RscTestControlTypes"",'GUI'] call 	(uinamespace getvariable 'BIS_fnc_initDisplay')";
	scriptName = "RscTestControlTypes";
	scriptPath = "GUI";
	class Controls
	{
		class _CT_ACTIVETEXT
		{
			access = 0;
			blinkingPeriod = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {1, 0.5, 0, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 11;
			onButtonClick = "debugLog ['Log: onButtonClick',ctrlClassname (_this select 0),_this]; false";
			onButtonDown = "debugLog ['Log: onButtonDown',ctrlClassname (_this select 0),_this]; false";
			onButtonUp = "debugLog ['Log: onButtonUp',ctrlClassname (_this select 0),_this]; false";
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			soundClick[] = {"", 1, 1};
			soundEnter[] = {"", 1, 1};
			soundEscape[] = {"", 1, 1};
			soundPush[] = {"", 1, 1};
			style = 0;
			text = "CT_ACTIVETEXT";
			tooltip = "CT_ACTIVETEXT";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 11;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_BUTTON
		{
			access = 0;
			blinkingPeriod = 0;
			borderSize = 0.01;
			colorBackground[] = {0.2, 0.2, 0.2, 1};
			colorBackgroundActive[] = {0, 0, 0, 1};
			colorBackgroundDisabled[] = {0, 0, 0, 0.5};
			colorBorder[] = {1, 1, 1, 1};
			colorDisabled[] = {1, 1, 1, 0.5};
			colorFocused[] = {1, 0.5, 0, 1};
			colorShadow[] = {0, 0, 0, 0.2};
			colorText[] = {1, 1, 1, 1};
			default = 1;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 1;
			offsetPressedX = 0.0075;
			offsetPressedY = 0.01;
			offsetX = 0.0075;
			offsetY = 0.01;
			onButtonClick = "debugLog ['Log: onButtonClick',ctrlClassname (_this select 0),_this]; false";
			onButtonDown = "debugLog ['Log: onButtonDown',ctrlClassname (_this select 0),_this]; false";
			onButtonUp = "debugLog ['Log: onButtonUp',ctrlClassname (_this select 0),_this]; false";
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			period = 1;
			periodFocus = 2;
			periodOver = 0.5;
			shadow = 1;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
			soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
			soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
			soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
			style = 0;
			text = "CT_BUTTON";
			tooltip = "CT_BUTTON";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 1;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "3 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class KeyHints
			{
				class A
				{
					hint = "KEY_XBOX_A";
					key = "0x00050000 + 0";
				};
			};
		};
		class _CT_CHECKBOX
		{
			access = 0;
			blinkingPeriod = 0;
			color[] = {1, 1, 1, 0.7};
			colorBackground[] = {0, 0, 0, 0};
			colorBackgroundDisabled[] = {0, 0, 0, 0};
			colorBackgroundFocused[] = {0, 0, 0, 0};
			colorBackgroundHover[] = {0, 0, 0, 0};
			colorBackgroundPressed[] = {0, 0, 0, 0};
			colorDisabled[] = {1, 1, 1, 0.2};
			colorFocused[] = {1, 1, 1, 1};
			colorHover[] = {1, 1, 1, 1};
			colorPressed[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 77;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			show = 1;
			soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
			soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
			soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
			soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
			style = "0x00 + 0x10";
			textureChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
			textureDisabledChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
			textureDisabledUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
			textureFocusedChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
			textureFocusedUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
			textureHoverChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
			textureHoverUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
			texturePressedChecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_checked_ca.paa";
			texturePressedUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
			textureUnchecked = "\A3\Ui_f\data\GUI\RscCommon\RscCheckBox\CheckBox_unchecked_ca.paa";
			tooltip = "CT_CHECKBOX";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 77;
			w = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "29 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "20 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_CHECKBOXES
		{
			access = 0;
			blinkingPeriod = 0;
			checked_strings[] = {"Alpha", "Bravo", "Charlie", "Delta"};
			color[] = {0, 0, 0, 0};
			colorDisable[] = {0, 0, 0, 0};
			colorSelect[] = {0, 0, 0, 0};
			colorSelectedBg[] = {1, 0.5, 0, 1};
			colorText[] = {1, 1, 1, 0.5};
			colorTextDisable[] = {0, 0, 0, 0};
			colorTextSelect[] = {1, 1, 1, 1};
			columns = 2;
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "2 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 7;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onCheckBoxesSelChanged = "debugLog ['Log: onCheckBoxesSelChanged',ctrlClassname (_this select 0),_this]; false";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			rows = 2;
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			strings[] = {"A", "B", "C", "D"};
			style = 0;
			text = "CT_CHECKBOXES";
			tooltip = "CT_CHECKBOXES";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 7;
			values[] = {1, 2, 3, 4};
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "18 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_COMBO
		{
			access = 0;
			arrowEmpty = "\A3\ui_f\data\GUI\RscCommon\rsccombo\arrow_combo_ca.paa";
			arrowFull = "\A3\ui_f\data\GUI\RscCommon\rsccombo\arrow_combo_active_ca.paa";
			blinkingPeriod = 0;
			colorBackground[] = {0.2, 0.2, 0.2, 1};
			colorDisabled[] = {1, 1, 1, 0.5};
			colorPicture[] = {1, 0.5, 0, 1};
			colorPictureDisabled[] = {1, 1, 1, 0.5};
			colorPictureSelect[] = {1, 1, 1, 1};
			colorSelect[] = {1, 1, 1, 1};
			colorSelectBackground[] = {1, 0.5, 0, 1};
			colorText[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 4;
			maxHistoryDelay = 1;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onLBSelChanged = "debugLog ['Log: onLBSelChanged',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			soundCollapse[] = {"\A3\ui_f\data\sound\RscCombo\soundCollapse", 0.1, 1};
			soundExpand[] = {"\A3\ui_f\data\sound\RscCombo\soundExpand", 0.1, 1};
			soundSelect[] = {"\A3\ui_f\data\sound\RscCombo\soundSelect", 0.1, 1};
			style = "0x00 + 0x10";
			tooltip = "CT_COMBO";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 4;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			wholeHeight = "5 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "9 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class ComboScrollBar
			{
				arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
				arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
				border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
				color[] = {1, 1, 1, 1};
				height = 0;
				scrollSpeed = 0.01;
				thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
				width = 0;
			};
		};
		class _CT_CONTROLS_GROUP
		{
			access = 0;
			blinkingPeriod = 0;
			enable = 1;
			fade = 0;
			h = "3 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 15;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			show = 1;
			style = 16;
			type = 15;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "9 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class Controls
			{
				class _CT_STATIC: _CT_STATIC
				{
					blinkingPeriod = 0;
					h = "5 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
					idc = 1300;
					style = 48;
					text = "#(ai,512,512,1)perlinNoise(512,128,0,1)";
					tooltip = "CT_CONTROLS_GROUP";
					w = "20 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
					x = 0;
					y = 0;
				};
			};
			class HScrollBar
			{
				arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
				arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
				border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
				color[] = {1, 1, 1, 1};
				height = 0.028;
				scrollSpeed = 0.01;
				thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
				width = 0;
			};
			class VScrollBar
			{
				arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
				arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
				autoScrollDelay = 1;
				autoScrollEnabled = 1;
				autoScrollRewind = 1;
				autoScrollSpeed = 1;
				border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
				color[] = {1, 1, 1, 1};
				height = 0;
				scrollSpeed = 0.01;
				thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
				width = 0.021;
			};
		};
		class _CT_EDIT
		{
			access = 0;
			autocomplete = "scripting";
			blinkingPeriod = 0;
			canModify = 1;
			colorDisabled[] = {1, 1, 1, 0.5};
			colorSelection[] = {1, 0.5, 0, 1};
			colorText[] = {0, 0, 0, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 2;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			style = 0;
			text = "CT_EDIT";
			tooltip = "CT_EDIT";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 2;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "5 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_HTML
		{
			access = 0;
			blinkingPeriod = 0;
			colorBackground[] = {0.2, 0.2, 0.2, 1};
			colorBold[] = {1, 1, 1, 1};
			colorLink[] = {1, 1, 1, 1};
			colorLinkActive[] = {1, 0.5, 0, 1};
			colorPicture[] = {1, 1, 1, 1};
			colorPictureBorder[] = {0, 0, 0, 0};
			colorPictureLink[] = {1, 1, 1, 1};
			colorPictureSelected[] = {1, 1, 1, 1};
			colorText[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			filename = "a3\ui_f\data\html\RscFeedback.html";
			h = "1.5 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 9;
			nextPage = "\A3\ui_f\data\gui\rsccommon\rschtml\arrow_right_ca.paa";
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onHTMLLink = "debugLog ['Log: onHTMLLink',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			prevPage = "\A3\ui_f\data\gui\rsccommon\rschtml\arrow_left_ca.paa";
			show = 1;
			style = 0;
			tooltip = "CT_HTML";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 9;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "23 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class H1: P {};
			class H2: P {};
			class H3: P {};
			class H4: P {};
			class H5: P {};
			class H6: P {};
			class P
			{
				align = "left";
				font = "RobotoCondensed";
				fontBold = "RobotoCondensedBold";
				sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			};
		};
		class _CT_LISTBOX
		{
			access = 0;
			blinkingPeriod = 0;
			canDrag = 1;
			colorBackground[] = {0.2, 0.2, 0.2, 1};
			colorDisabled[] = {1, 1, 1, 0.5};
			colorPicture[] = {1, 0.5, 0, 1};
			colorPictureDisabled[] = {1, 1, 1, 0.5};
			colorPictureRight[] = {1, 0.5, 0, 1};
			colorPictureRightDisabled[] = {1, 1, 1, 0.5};
			colorPictureRightSelected[] = {1, 1, 1, 1};
			colorPictureSelected[] = {1, 1, 1, 1};
			colorSelect[] = {1, 1, 1, 1};
			colorSelect2[] = {1, 1, 1, 1};
			colorSelectBackground[] = {1, 0.5, 0, 1};
			colorSelectBackground2[] = {0, 0, 0, 1};
			colorShadow[] = {0, 0, 0, 0.5};
			colorText[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "3 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 5;
			itemSpacing = 0;
			maxHistoryDelay = 1;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onLBDblClick = "debugLog ['Log: onLBDblClick',ctrlClassname (_this select 0),_this]; false";
			onLBDrag = "debugLog ['Log: onLBDrag',ctrlClassname (_this select 0),_this]; false";
			onLBDragging = "debugLog ['Log: onLBDragging',ctrlClassname (_this select 0),_this]; false";
			onLBDrop = "debugLog ['Log: onLBDrop',ctrlClassname (_this select 0),_this]; false";
			onLBSelChanged = "debugLog ['Log: onLBSelChanged',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			period = 1;
			rowHeight = "1.5 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			soundSelect[] = {"\A3\ui_f\data\sound\RscListbox\soundSelect", 0.09, 1};
			style = "0x00 + 0x10";
			tooltip = "CT_LISTBOX";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 5;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "11 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class ListScrollBar
			{
				arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
				arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
				border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
				color[] = {1, 1, 1, 1};
				height = 0;
				scrollSpeed = 0.01;
				thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
				width = 0;
			};
		};
		class _CT_LISTNBOX
		{
			access = 0;
			blinkingPeriod = 0;
			colorDisabled[] = {1, 1, 1, 0.5};
			colorSelect[] = {1, 1, 1, 1};
			colorSelect2[] = {1, 1, 1, 1};
			colorSelectBackground[] = {1, 0.5, 0, 1};
			colorSelectBackground2[] = {0, 0, 0, 1};
			colorShadow[] = {0, 0, 0, 0.5};
			colorText[] = {1, 1, 1, 1};
			columns[] = {0.1, 0.4};
			default = 0;
			drawSideArrows = 1;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "3 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 102;
			idcLeft = 1000;
			idcRight = 1001;
			maxHistoryDelay = 1;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onLBDblClick = "debugLog ['Log: onLBDblClick',ctrlClassname (_this select 0),_this]; false";
			onLBSelChanged = "debugLog ['Log: onLBSelChanged',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			period = 1;
			rowHeight = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			soundSelect[] = {"\A3\ui_f\data\sound\RscListbox\soundSelect", 0.09, 1};
			style = "0x00 + 0x10";
			tooltip = "CT_LISTNBOX";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 102;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "29 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "15 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class ListScrollBar
			{
				arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
				arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
				border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
				color[] = {1, 1, 1, 1};
				height = 0;
				scrollSpeed = 0.01;
				thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
				width = 0;
			};
		};
		class _CT_LISTNBOX_LEFT: _CT_LISTNBOX_RIGHT
		{
			idc = 1001;
			text = ">";
		};
		class _CT_LISTNBOX_RIGHT: _CT_BUTTON
		{
			borderSize = 0;
			colorShadow[] = {0, 0, 0, 0};
			idc = 1000;
			text = "<";
		};
		class _CT_MAP
		{
			access = 0;
			alphaFadeEndScale = 0.01;
			alphaFadeStartScale = 0.1;
			blinkingPeriod = 0;
			colorBackground[] = {1, 1, 1, 1};
			colorCountlines[] = {0.6, 0.4, 0.2, 0.3};
			colorCountlinesWater[] = {0.5, 0.6, 0.7, 0.3};
			colorForest[] = {0.6, 0.8, 0.4, 0.5};
			colorForestBorder[] = {0.6, 0.8, 0.4, 1};
			colorGrid[] = {0.1, 0.1, 0.1, 0.6};
			colorGridMap[] = {0.1, 0.1, 0.1, 0.6};
			colorInactive[] = {1, 1, 0, 0.5};
			colorLevels[] = {0.3, 0.2, 0.1, 0.5};
			colorMainCountlines[] = {0.6, 0.4, 0.2, 0.5};
			colorMainCountlinesWater[] = {0.5, 0.6, 0.7, 0.6};
			colorMainRoads[] = {0.9, 0.5, 0.3, 1};
			colorMainRoadsFill[] = {1, 0.6, 0.4, 1};
			colorNames[] = {1.1, 0.1, 1.1, 0.9};
			colorOutside[] = {0, 0, 0, 1};
			colorPowerLines[] = {0.1, 0.1, 0.1, 1};
			colorRailWay[] = {0.8, 0.2, 0, 1};
			colorRoads[] = {0.7, 0.7, 0.7, 1};
			colorRoadsFill[] = {1, 1, 1, 1};
			colorRocks[] = {0, 0, 0, 0.3};
			colorRocksBorder[] = {0, 0, 0, 1};
			colorSea[] = {0.4, 0.6, 0.8, 0.5};
			colorText[] = {0, 0, 0, 1};
			colorTracks[] = {0.8, 0.8, 0.7, 0.2};
			colorTracksFill[] = {0.8, 0.7, 0.7, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			fontGrid = "TahomaB";
			fontInfo = "RobotoCondensed";
			fontLabel = "RobotoCondensed";
			fontLevel = "TahomaB";
			fontNames = "RobotoCondensed";
			fontUnits = "TahomaB";
			h = "6 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 100;
			maxSatelliteAlpha = 0.85;
			moveOnEdges = 1;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onDraw = "";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			ptsPerSquareCLn = 10;
			ptsPerSquareCost = 10;
			ptsPerSquareExp = 10;
			ptsPerSquareFor = 9;
			ptsPerSquareForEdge = 9;
			ptsPerSquareObj = 9;
			ptsPerSquareRoad = 6;
			ptsPerSquareSea = 5;
			ptsPerSquareTxt = 20;
			scaleDefault = 0.16;
			scaleMax = 1;
			scaleMin = 0.001;
			show = 1;
			showCountourInterval = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			sizeExGrid = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 0.5";
			sizeExInfo = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 0.5";
			sizeExLabel = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 0.5";
			sizeExLevel = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 0.5";
			sizeExNames = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 0.5";
			sizeExUnits = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 0.5";
			style = 48;
			text = "#(argb,8,8,3)color(1,1,1,1)";
			tooltip = "CT_MAP";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 101;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "29 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class ActiveMarker
			{
				color[] = {0, 0, 0, 1};
				size = 2;
			};
			class Bunker: Waypoint {};
			class Bush: Waypoint {};
			class BusStop: Waypoint {};
			class Chapel: Waypoint {};
			class Church: Waypoint {};
			class Command: Waypoint {};
			class Cross: Waypoint {};
			class CustomMark: Waypoint {};
			class Fortress: Waypoint {};
			class Fountain: Waypoint {};
			class FuelStation: Waypoint {};
			class Hospital: Waypoint {};
			class Lighthouse: Waypoint {};
			class Power: Waypoint {};
			class PowerSolar: Waypoint {};
			class PowerWave: Waypoint {};
			class PowerWind: Waypoint {};
			class Quay: Waypoint {};
			class Rock: Waypoint {};
			class Ruin: Waypoint {};
			class Shipwreck: Waypoint {};
			class SmallTree: Waypoint {};
			class Stack: Waypoint {};
			class Task
			{
				coefMax = 1;
				coefMin = 1;
				color[] = {1, 1, 0, 1};
				colorCanceled[] = {0, 0, 0, 0.5};
				colorCreated[] = {0, 0, 0, 1};
				colorDone[] = {0, 1, 0, 1};
				colorFailed[] = {1, 0, 0, 1};
				icon = "#(argb,8,8,3)color(1,1,1,1)";
				iconCanceled = "#(argb,8,8,3)color(1,1,1,1)";
				iconCreated = "#(argb,8,8,3)color(1,1,1,1)";
				iconDone = "#(argb,8,8,3)color(1,1,1,1)";
				iconFailed = "#(argb,8,8,3)color(1,1,1,1)";
				importance = 1;
				size = 8;
			};
			class Tourism: Waypoint {};
			class Transmitter: Waypoint {};
			class Tree: Waypoint {};
			class ViewTower: Waypoint {};
			class Watertower: Waypoint {};
			class Waypoint
			{
				coefMax = 1;
				coefMin = 4;
				color[] = {0, 0, 0, 1};
				icon = "#(argb,8,8,3)color(0,0,0,1)";
				importance = 1;
				size = 2;
			};
			class WaypointCompleted: Waypoint {};
		};
		class _CT_MAP_MAIN: _CT_MAP
		{
			access = 0;
			blinkingPeriod = 0;
			default = 0;
			enable = 1;
			fade = 0;
			h = "6 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 101;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onDraw = "";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			show = 1;
			showCountourInterval = 1;
			style = 48;
			tooltip = "CT_MAP_MAIN";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 101;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "29 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "8 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class Legend
			{
				color[] = {0, 0, 0, 1};
				colorBackground[] = {1, 1, 1, 1};
				font = "RobotoCondensed";
				h = "4 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				sizeEx = "0.8 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				w = "8 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
				x = "30 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
				y = "9 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			};
		};
		class _CT_PROGRESS
		{
			access = 0;
			blinkingPeriod = 0;
			colorBar[] = {1, 1, 1, 1};
			colorFrame[] = {0, 0, 0, 1};
			default = 0;
			enable = 1;
			fade = 0;
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 8;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			show = 1;
			style = 0;
			texture = "#(argb,8,8,3)color(1,1,1,1)";
			tooltip = "CT_PROGRESS";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 8;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "21 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_SHORTCUTBUTTON
		{
			access = 0;
			animTextureDefault = "#(argb,8,8,3)color(1,1,1,1)";
			animTextureDisabled = "#(argb,8,8,3)color(1,1,1,1)";
			animTextureFocused = "#(argb,8,8,3)color(1,1,1,1)";
			animTextureNormal = "#(argb,8,8,3)color(1,1,1,1)";
			animTextureOver = "#(argb,8,8,3)color(1,1,1,1)";
			animTexturePressed = "#(argb,8,8,3)color(1,1,1,1)";
			blinkingPeriod = 0;
			color[] = {1, 1, 1, 1};
			color2[] = {1, 1, 1, 1};
			colorBackground[] = {0.2, 0.2, 0.2, 1};
			colorBackground2[] = {0, 0, 0, 1};
			colorBackgroundActive[] = {0, 0, 0, 1};
			colorBackgroundFocused[] = {1, 0.5, 0, 1};
			colorDisabled[] = {1, 1, 1, 0.5};
			colorFocused[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 16;
			onButtonClick = "debugLog ['Log: onButtonClick',ctrlClassname (_this select 0),_this]; false";
			onButtonDown = "debugLog ['Log: onButtonDown',ctrlClassname (_this select 0),_this]; false";
			onButtonUp = "debugLog ['Log: onButtonUp',ctrlClassname (_this select 0),_this]; false";
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			period = 1;
			periodFocus = 1;
			periodOver = 0.5;
			shadow = 1;
			shortcuts[] = {"0x00050000 + 0", 28, 57, 156};
			show = 1;
			size = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			sizeEx = 0;
			soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
			soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
			soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
			soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
			style = 0;
			text = "CT_SHORTCUTBUTTON";
			textureNoShortcut = "#(argb,8,8,3)color(1,1,1,1)";
			tooltip = "CT_SHORTCUTBUTTON";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 16;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "13 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class Attributes
			{
				align = "left";
				color = "#ffffff";
				font = "RobotoCondensed";
				shadow = 0;
			};
			class HitZone
			{
				bottom = 0;
				left = 0;
				right = 0;
				top = 0;
			};
			class ShortcutPos
			{
				h = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				left = 0;
				top = 0;
				w = "(			((safezoneW / safezoneH) min 1.2) / 40)";
			};
			class TextPos
			{
				bottom = 0;
				left = "(			((safezoneW / safezoneH) min 1.2) / 40)";
				right = 0;
				top = 0;
			};
		};
		class _CT_SLIDER
		{
			access = 0;
			blinkingPeriod = 0;
			color[] = {0, 0, 0, 1};
			colorActive[] = {1, 0.5, 0, 1};
			colorDisabled[] = {1, 1, 1, 0.5};
			default = 0;
			enable = 1;
			fade = 0;
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 3;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			onSliderPosChanged = "debugLog ['Log: onSliderPosChanged',ctrlClassname (_this select 0),_this]; false";
			show = 1;
			sliderPosition = 42;
			sliderRange[] = {0, 100};
			style = 1024;
			tooltip = "CT_SLIDER";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 3;
			w = "7 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "7 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class Title
			{
				colorActive[] = {1, 0.5, 0, 1};
				colorBase[] = {1, 1, 1, 1};
				idc = -1;
			};
			class Value
			{
				colorActive[] = {1, 0.5, 0, 1};
				colorBase[] = {1, 1, 1, 1};
				format = "%.f";
				idc = 1200;
				type = "SPTPlain";
			};
		};
		class _CT_SLIDER_Value: _CT_STATIC
		{
			blinkingPeriod = 0;
			colorBackground[] = {0, 0, 0, 0};
			fixedWidth = 0;
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 1200;
			style = 2;
			w = "3 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "8 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "6.75 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_STATIC
		{
			access = 0;
			autoplay = 0;
			blinkingPeriod = 1;
			colorBackground[] = {0.2, 0.2, 0.2, 1};
			colorShadow[] = {0, 0, 0, 0.5};
			colorText[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			fixedWidth = 1;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 0;
			lineSpacing = 1;
			loops = 0;
			moving = 0;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			onVideoStopped = "debugLog ['Log: onVideoStopped',ctrlClassname (_this select 0),_this]; false";
			shadow = 1;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			style = "0x00 + 0x10";
			text = "CT_STATIC";
			tileH = 1;
			tileW = 1;
			tooltip = "CT_STATIC";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 0;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_STRUCTURED_TEXT
		{
			access = 0;
			blinkingPeriod = 0;
			colorBackground[] = {0.2, 0.2, 0.2, 1};
			default = 0;
			enable = 1;
			fade = 0;
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 13;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			show = 1;
			size = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			style = 0;
			text = "<img image='\A3\Ui_f\data\GUI\Cfg\Ranks\general_gs.paa' size='0.5' />CT_<t size='0.8' underline='1' color='#ffff8000' font='PuristaBold' shadow='1' shadowColor='#000000'><a href='https://arma3.com'>STRUCTURED</a></t>_TEXT";
			tooltip = "CT_STRUCTURED_TEXT";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 13;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "7 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class Attributes
			{
				align = "left";
				color = "#ffffff";
				colorLink = "#ff8000";
				font = "RobotoCondensed";
				size = 1;
			};
		};
		class _CT_TOOLBOX
		{
			access = 0;
			blinkingPeriod = 0;
			color[] = {0, 0, 0, 0};
			colorDisable[] = {0, 0, 0, 0};
			colorSelect[] = {0, 0, 0, 0};
			colorSelectedBg[] = {1, 0.5, 0, 1};
			colorText[] = {1, 1, 1, 1};
			colorTextDisable[] = {0, 0, 0, 0};
			colorTextSelect[] = {1, 1, 1, 1};
			columns = 2;
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "2 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 6;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			onToolBoxSelChanged = "debugLog ['Log: onToolBoxSelChanged',ctrlClassname (_this select 0),_this]; false";
			rows = 2;
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			strings[] = {"Alpha", "Bravo", "Charlie", "Delta"};
			style = 2;
			tooltip = "CT_TOOLBOX";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 6;
			values[] = {1, 2, 3, 4};
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "1 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "15 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_TREE
		{
			access = 0;
			blinkingPeriod = 0;
			colorArrow[] = {0, 0, 0, 0};
			colorBackground[] = {0.2, 0.2, 0.2, 1};
			colorBorder[] = {0, 0, 0, 1};
			colorDisabled[] = {0, 0, 0, 0};
			colorMarked[] = {1, 0.5, 0, 0.5};
			colorMarkedSelected[] = {1, 0.5, 0, 1};
			colorMarkedText[] = {1, 1, 1, 1};
			colorSelect[] = {1, 0.5, 0, 1};
			colorSelectText[] = {1, 1, 1, 1};
			colorText[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			expandedTexture = "A3\ui_f\data\gui\rsccommon\rsctree\expandedTexture_ca.paa";
			expandOnDoubleclick = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "3 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			hiddenTexture = "A3\ui_f\data\gui\rsccommon\rsctree\hiddenTexture_ca.paa";
			idc = 12;
			maxHistoryDelay = 1;
			multiselectEnabled = 1;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			onTreeCollapsed = "debugLog ['Log: onTreeCollapsed',ctrlClassname (_this select 0),_this]; false";
			onTreeDblClick = "debugLog ['Log: onTreeDblClick',ctrlClassname (_this select 0),_this]; false";
			onTreeExpanded = "debugLog ['Log: onTreeExpanded',ctrlClassname (_this select 0),_this]; false";
			onTreeLButtonDown = "debugLog ['Log: onTreeLButtonDown',ctrlClassname (_this select 0),_this]; false";
			onTreeMouseExit = "debugLog ['Log: onTreeMouseExit',ctrlClassname (_this select 0),_this]; false";
			onTreeSelChanged = "debugLog ['Log: onTreeSelChanged',ctrlClassname (_this select 0),_this]; false";
			shadow = 1;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			style = 0;
			tooltip = "CT_TREE";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 12;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "3 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class ScrollBar
			{
				arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
				arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
				border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
				color[] = {1, 1, 1, 1};
				height = 0;
				scrollSpeed = 0.01;
				thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
				width = 0;
			};
		};
		class _CT_XBUTTON
		{
			access = 0;
			blinkingPeriod = 0;
			color[] = {1, 1, 1, 1};
			colorActive[] = {1, 1, 1, 1};
			colorActive2[] = {1, 1, 1, 1};
			colorActiveBackground[] = {1, 0.5, 0, 1};
			colorActiveBackground2[] = {0, 0, 0, 1};
			colorBackground[] = {0, 0, 0, 0};
			colorDisabled[] = {0, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 41;
			onButtonClick = "debugLog ['Log: onButtonClick',ctrlClassname (_this select 0),_this]; false";
			onButtonDown = "debugLog ['Log: onButtonDown',ctrlClassname (_this select 0),_this]; false";
			onButtonUp = "debugLog ['Log: onButtonUp',ctrlClassname (_this select 0),_this]; false";
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			period = 1;
			shadow = 0;
			show = 1;
			size = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			soundClick[] = {"\A3\ui_f\data\sound\RscButton\soundClick", 0.09, 1};
			soundEnter[] = {"\A3\ui_f\data\sound\RscButton\soundEnter", 0.09, 1};
			soundEscape[] = {"\A3\ui_f\data\sound\RscButton\soundEscape", 0.09, 1};
			soundPush[] = {"\A3\ui_f\data\sound\RscButton\soundPush", 0.09, 1};
			style = 0;
			text = "CT_XBUTTON";
			tooltip = "CT_XBUTTON";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 41;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "15 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_XCOMBO
		{
			access = 0;
			blinkingPeriod = 0;
			colorBorder[] = {1, 0, 1, 1};
			colorDisabled[] = {1, 1, 1, 0.5};
			colorDisabledBorder[] = {0, 1, 1, 1};
			colorSelect[] = {1, 1, 1, 1};
			colorSelect2[] = {1, 1, 1, 1};
			colorSelectBackground2[] = {0, 0, 0, 1};
			colorSelectBorder[] = {1, 1, 1, 1};
			colorText[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 44;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onLBDblClick = "debugLog ['Log: onLBDblClick',ctrlClassname (_this select 0),_this]; false";
			onLBListSelChanged = "debugLog ['Log: onLBListSelChanged',ctrlClassname (_this select 0),_this]; false";
			onLBSelChanged = "debugLog ['Log: onLBSelChanged',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseEnter = "debugLog ['Log: onMouseEnter',ctrlClassname (_this select 0),_this]; false";
			onMouseExit = "debugLog ['Log: onMouseExit',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			soundCollapse[] = {"\A3\ui_f\data\sound\RscCombo\soundCollapse", 0.1, 1};
			soundExpand[] = {"\A3\ui_f\data\sound\RscCombo\soundExpand", 0.1, 1};
			soundSelect[] = {"\A3\ui_f\data\sound\RscCombo\soundSelect", 0.1, 1};
			style = "0x00 + 0x10";
			tooltip = "CT_XCOMBO";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 44;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "22 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class List
			{
				colorBackground[] = {0.2, 0.2, 0.2, 1};
				colorBorder[] = {1, 1, 1, 1};
				colorSelect[] = {1, 1, 1, 1};
				colorSelectBackground[] = {1, 0.5, 0, 1};
				colorText[] = {1, 1, 1, 1};
				h = "5 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				rowHeight = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
				x = "22 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
				y = "22 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			};
			class ScrollBar
			{
				arrowEmpty = "\A3\ui_f\data\gui\cfg\scrollbar\arrowEmpty_ca.paa";
				arrowFull = "\A3\ui_f\data\gui\cfg\scrollbar\arrowFull_ca.paa";
				border = "\A3\ui_f\data\gui\cfg\scrollbar\border_ca.paa";
				color[] = {1, 1, 1, 1};
				height = 0;
				scrollSpeed = 0.01;
				thumb = "\A3\ui_f\data\gui\cfg\scrollbar\thumb_ca.paa";
				width = 0;
			};
			class Title
			{
				colorBackground[] = {0.2, 0.2, 0.2, 1};
				colorBorder[] = {0, 0, 0, 1};
				colorDisabled[] = {1, 1, 1, 0.5};
				colorDisabledBorder[] = {1, 1, 1, 1};
				colorSelect[] = {1, 1, 1, 1};
				colorSelectBackground[] = {1, 0.5, 0, 1};
				colorSelectBorder[] = {0, 0, 0, 1};
				colorText[] = {1, 1, 1, 1};
				font = "RobotoCondensed";
				h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				size = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
				text = "CT_XCOMBO";
				w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
				x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
				y = "21 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			};
		};
		class _CT_XLISTBOX
		{
			access = 0;
			arrowEmpty = "\A3\ui_f\data\gui\cfg\slider\arrowEmpty_ca.paa";
			arrowFull = "\A3\ui_f\data\gui\cfg\slider\arrowFull_ca.paa";
			blinkingPeriod = 0;
			border = "\A3\ui_f\data\gui\cfg\slider\border_ca.paa";
			color[] = {1, 1, 1, 1};
			colorActive[] = {1, 0.5, 0, 1};
			colorDisabled[] = {1, 1, 1, 0.5};
			colorSelect[] = {1, 0.5, 0, 1};
			colorText[] = {1, 1, 1, 1};
			default = 0;
			enable = 1;
			fade = 0;
			font = "RobotoCondensed";
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 42;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onLBDblClick = "debugLog ['Log: onLBDblClick',ctrlClassname (_this select 0),_this]; false";
			onLBSelChanged = "debugLog ['Log: onLBSelChanged',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			shadow = 0;
			show = 1;
			sizeEx = "(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			soundSelect[] = {"\A3\ui_f\data\sound\RscListbox\soundSelect", 0.09, 1};
			style = "0x400 + 0x02 + 0x10";
			tooltip = "CT_XLISTBOX";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 42;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "17 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
		class _CT_XSLIDER
		{
			access = 0;
			arrowEmpty = "\A3\ui_f\data\gui\cfg\slider\arrowEmpty_ca.paa";
			arrowFull = "\A3\ui_f\data\gui\cfg\slider\arrowFull_ca.paa";
			blinkingPeriod = 0;
			border = "\A3\ui_f\data\gui\cfg\slider\border_ca.paa";
			color[] = {1, 1, 1, 1};
			colorActive[] = {1, 0.5, 0, 1};
			colorDisabled[] = {1, 1, 1, 0.5};
			default = 0;
			enable = 1;
			fade = 0;
			h = "1 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
			idc = 43;
			onCanDestroy = "debugLog ['Log: onCanDestroy',ctrlClassname (_this select 0),_this]; true";
			onDestroy = "debugLog ['Log: onDestroy',ctrlClassname (_this select 0),_this]; false";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			onSliderPosChanged = "debugLog ['Log: onSliderPosChanged',ctrlClassname (_this select 0),_this]; false";
			show = 1;
			sliderPosition = 42;
			sliderRange[] = {0, 100};
			style = 1024;
			thumb = "#(argb,8,8,3)color(1,1,1,1)";
			tooltip = "CT_XSLIDER";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 43;
			w = "10 * 					(			((safezoneW / safezoneH) min 1.2) / 40)";
			x = "12 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "19 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			class Title
			{
				colorActive[] = {1, 0.5, 0, 1};
				colorBase[] = {1, 1, 1, 1};
				idc = -1;
			};
			class Value
			{
				colorActive[] = {1, 0.5, 0, 1};
				colorBase[] = {1, 1, 1, 1};
				format = "%.f";
				idc = -1;
				type = "SPTPlain";
			};
		};
	};
	class ControlsBackground
	{
		class Background: RscText
		{
			colorBackground[] = {0.5, 0.5, 0.5, 1};
			h = "(			((safezoneW / safezoneH) min 1.2) / 1.2)";
			moving = 1;
			w = "((safezoneW / safezoneH) min 1.2)";
			x = "(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
		};
	};
	class Objects
	{
		class _CT_OBJECT
		{
			access = 0;
			blinkingPeriod = 0;
			direction[] = {0, 0, 1};
			enable = 1;
			idc = 80;
			model = "\a3\Ui_f\objects\Watch.p3d";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onObjectMoved = "debugLog ['Log: onObjectMoved',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			scale = 2;
			show = 1;
			style = 0;
			tooltip = "CT_OBJECT";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 80;
			up[] = {0, 1, 0};
			x = "26 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "4 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			z = 1;
		};
		class _CT_OBJECT_CONTAINER
		{
			access = 0;
			blinkingPeriod = 0;
			direction[] = {1, 0, 0.5};
			enable = 1;
			enableZoom = 1;
			idc = 82;
			inBack = 0;
			model = "\A3\Misc_F\Helpers\UserTexture1m.p3d";
			scale = 0.2;
			show = 1;
			style = 0;
			tooltip = "CT_OBJECT";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 82;
			up[] = {0.5, 1, 0};
			x = "26 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			xBack = "25 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "21 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			yBack = "12 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			z = 1;
			zBack = 2;
			zoomDuration = 0.5;
			class Areas
			{
				class UserTexture
				{
					selection = "usertexture";
					class Controls
					{
						class _CT_STATIC
						{
							colorBackground[] = {0, 0, 0, 1};
							colorText[] = {1, 1, 1, 1};
							font = "RobotoCondensed";
							h = 1;
							idc = 1100;
							lineSpacing = 1;
							sizeEx = "6 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25)";
							style = "0x00 + 0x02 + 0x10";
							text = "\nCT_OBJECT\n_CONTAINER";
							type = 0;
							w = 1;
							x = 0;
							y = 0;
						};
					};
				};
			};
		};
		class _CT_OBJECT_ZOOM
		{
			access = 0;
			blinkingPeriod = 0;
			direction[] = {0, 1, 1};
			enable = 1;
			enableZoom = 1;
			idc = 81;
			inBack = 0;
			model = "\a3\Ui_f\objects\Compass.p3d";
			onKeyDown = "debugLog ['Log: onKeyDown',ctrlClassname (_this select 0),_this]; false";
			onKeyUp = "debugLog ['Log: onKeyUp',ctrlClassname (_this select 0),_this]; false";
			onKillFocus = "debugLog ['Log: onKillFocus',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonClick = "debugLog ['Log: onMouseButtonClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDblClick = "debugLog ['Log: onMouseButtonDblClick',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonDown = "debugLog ['Log: onMouseButtonDown',ctrlClassname (_this select 0),_this]; false";
			onMouseButtonUp = "debugLog ['Log: onMouseButtonUp',ctrlClassname (_this select 0),_this]; false";
			onMouseHolding = "";
			onMouseMoving = "";
			onMouseZChanged = "debugLog ['Log: onMouseZChanged',ctrlClassname (_this select 0),_this]; false";
			onObjectMoved = "debugLog ['Log: onObjectMoved',ctrlClassname (_this select 0),_this]; false";
			onSetFocus = "debugLog ['Log: onSetFocus',ctrlClassname (_this select 0),_this]; false";
			scale = 2;
			show = 1;
			style = 0;
			tooltip = "CT_OBJECT_ZOOM";
			tooltipColorBox[] = {1, 1, 1, 1};
			tooltipColorShade[] = {0, 0, 0, 1};
			tooltipColorText[] = {1, 1, 1, 1};
			type = 81;
			up[] = {0, 1, 0};
			x = "26 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			xBack = "26 * 					(			((safezoneW / safezoneH) min 1.2) / 40) + 		(safezoneX + (safezoneW - 					((safezoneW / safezoneH) min 1.2))/2)";
			y = "13 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			yBack = "13 * 					(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) + 		(safezoneY + (safezoneH - 					(			((safezoneW / safezoneH) min 1.2) / 1.2))/2)";
			z = 1;
			zBack = 2;
			zoomDuration = 0.5;
		};
	};
};
