class RscTree
{
	access = 0;
	borderSize = 0;
	colorArrow[] = {1, 1, 1, 1};
	colorBackground[] = {0, 0, 0, 0};
	colorBorder[] = {0, 0, 0, 0};
	colorDisabled[] = {1, 1, 1, 0.25};
	colorLines[] = {0, 0, 0, 0};
	colorMarked[] = {0.2, 0.3, 0.7, 1};
	colorMarkedSelected[] = {0, 0.5, 0.5, 1};
	colorMarkedText[] = {0, 0, 0, 1};
	colorPicture[] = {1, 1, 1, 1};
	colorPictureDisabled[] = {1, 1, 1, 0.25};
	colorPictureRight[] = {1, 1, 1, 1};
	colorPictureRightDisabled[] = {1, 1, 1, 0.25};
	colorPictureRightSelected[] = {0, 0, 0, 1};
	colorPictureSelected[] = {0, 0, 0, 1};
	colorSearch[] = {"(profilenamespace getvariable ['GUI_BCG_RGB_R',0.13])", "(profilenamespace getvariable ['GUI_BCG_RGB_G',0.54])", "(profilenamespace getvariable ['GUI_BCG_RGB_B',0.21])", "(profilenamespace getvariable ['GUI_BCG_RGB_A',0.8])"};
	colorSelect[] = {1, 1, 1, 0.7};
	colorSelectBackground[] = {0, 0, 0, 0.5};
	colorSelectText[] = {0, 0, 0, 1};
	colorText[] = {1, 1, 1, 1};
	deletable = 0;
	expandedTexture = "A3\ui_f\data\gui\rsccommon\rsctree\expandedTexture_ca.paa";
	expandOnDoubleclick = 1;
	fade = 0;
	font = "RobotoCondensed";
	h = 0.2;
	hiddenTexture = "A3\ui_f\data\gui\rsccommon\rsctree\hiddenTexture_ca.paa";
	maxHistoryDelay = 1;
	multiselectEnabled = 0;
	rowHeight = 0.0439091;
	shadow = 0;
	sizeEx = "(			(			(			((safezoneW / safezoneH) min 1.2) / 1.2) / 25) * 1)";
	style = 0;
	type = 12;
	w = 0.1;
	x = 0;
	y = 0;
	class ScrollBar: ScrollBar {};
};
